server:
  port: 8080
spring:
  application:
    name: mylibrarynew
  freemarker:
    suffix: .ftlh
    settings:
      number_format: 0.##
    cache: false
    charset: UTF-8
    content-type: text/html;charset=utf-8
    checkTemplateLocation: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: hkm2267070
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**

  jpa:
    open-in-view: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.library.bean
logging:
  level:
    com:
      library:
        mapper: debug
